### ISSUE TITLE
MambaYOLOWorldPAFPN is not in the mmyolo::model registry.

### ISSUE THREAD

**Issue by hezhengting** [Xuan-World/Mamba-YOLO-World#3]
I am trying to run image_demo as 
python demo/image_demo.py --config configs/mamba2_yolo_world_s.py \
 --checkpoint MambaYOLOWorld_s_pretrain_O365GoldG.pth \
 --image my_image_path \
 --text food

But i got error
KeyError: 'MambaYOLOWorldPAFPN is not in the mmyolo::model registry. Please check whether the value of `MambaYOLOWorldPAFPN` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

what could be the reason for this error?

**Comment by hezhengting** [comment]
never mind. I should set PYTHONPATH=path_of_Mamba-YOLO-World

**Comment by HandsLing** [comment]
@hezhengting how do you solve it?
