### ISSUE TITLE
supervision issue?

### ISSUE THREAD

**Issue by hezhengting** [Xuan-World/Mamba-YOLO-World#5]
run demo/image_demo.py and got the problem below. It looks supervision version is not compatible? Suggest to share requirements.txt. Thanks.

(py39_torch2.0.0_cu118) ubuntu@DESKTOP-QAKAUM1:/mnt/d/dev/mamba_yolo_world/Mamba-YOLO-World$ python demo/image_demo.py --config configs/mamba2_yolo_world_s.py \
 --check>  --checkpoint MambaYOLOWorld_s_pretrain_O365GoldG.pth \
mage /mn>  --image /mnt/e/public_dataset/coco/val2017/000000000785.jpg --text person
Loads checkpoint by local backend from path: MambaYOLOWorld_s_pretrain_O365GoldG.pth
[                                                  ] 0/1, elapsed: 0s, ETA:/home/ubuntu/anaconda3/envs/py39_torch2.0.0_cu118/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/mnt/d/dev/mamba_yolo_world/Mamba-YOLO-World/demo/image_demo.py", line 224, in <module>
    inference_detector(model,
  File "/mnt/d/dev/mamba_yolo_world/Mamba-YOLO-World/demo/image_demo.py", line 146, in inference_detector
    image = LABEL_ANNOTATOR.annotate(image, detections, labels=labels)
  File "/home/ubuntu/anaconda3/envs/py39_torch2.0.0_cu118/lib/python3.9/site-packages/supervision/annotators/core.py", line 820, in annotate
    text_background_xyxy = self.resolve_text_background_xyxy(

**Comment by Xuan-World** [comment]
**supervision==0.20.0**. I believe this environment should be automatically adjusted for compatibility by conda or other package management tools. The requirements.txt will be released later.
